sudo: false

language: node_js
node_js: "12"

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: Test
    script:
      - npm t
    - stage: Deploy Windows & Mac
    if: tag IS present
    os: osx
    osx_image: xcode10.1
    script:
      - npm run package:win
      - npm run package:mac
    - stage: Deploy Linux
    if: tag IS present
    os: Linux
    dist: trusty
    script:
      - npm run package:linux