cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

jobs:
  include:
    - stage: Test
      os: linux
      dist: trusty
      language: node_js
      node_js: 12
      script:
        - jest --coverage --updateSnapshot
    - stage: Deploy Mac
      if: (branch = master AND type = push) OR type = pull_request
      os: osx
      osx_image: xcode11
      language: node_js
      node_js: 12
      script:
        - npm run package:mac
    - stage: Deploy Linux
      os: linux
      services: docker
      language: generic
      node_js: 12
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
      if: (branch = master AND type = push) OR type = pull_request
      script:
        - |
          docker run --rm \
            -e ELECTRON_CACHE=$HOME/.cache/electron \
            -e ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder \
            -e CI=$CI \
            -e TRAVIS_PULL_REQUEST=$TRAVIS_PULL_REQUEST \
            -v ${PWD}:/product \
            -v ~/.cache/electron:/root/.cache/electron \
            -v ~/.cache/electron-builder:/root/.cache/electron-builder \
            electronuserland/builder:wine \
            /bin/bash -c "\
              npm install && \
              npm run package:linux \
              npm run package:win
            "
